name: lanai
description: A cross-platform application to search and browse millions of images from multiple data sources built using flutter.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: 3.7.1

dependencies:
  bloc: ^8.1.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  go_router: ^6.2.0
  intl: ^0.17.0

  pexels_repository:
    path: ./packages/pexels/pexels_repository/
  pixabay_repository:
    path: ./packages/pixabay/pixabay_repository/

dev_dependencies:
  bloc_test: ^9.1.1
  build_runner: ^2.3.3
  build_verify: ^3.1.0
  flutter_test:
    sdk: flutter
  go_router_builder: ^1.1.3
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
